export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  mercadoPagoAccessToken: process.env.MERCADO_PAGO_ACCESS_TOKEN ?? "",
  mercadoPagoBaseUrl: process.env.MERCADO_PAGO_BASE_URL ?? "https://api.mercadopago.com",
  mercadoPagoWebhookKey: process.env.MERCADO_PAGO_WEBHOOK_KEY ?? "",
  frontendUrl: process.env.FRONTEND_URL ?? "http://localhost:3000",
  serverUrl: process.env.SERVER_URL ?? process.env.FRONTEND_URL ?? "http://localhost:3000",
};
